### PR TITLE
chore(EIP): Change two parameters  in the List API from string to arrays

### PR DESCRIPTION
**Pull request by hmbig2**
Change some parameters  in the List API from string to arrays

**What this PR does / why we need it**:

**Which issue this PR fixes**:
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
fixes #xxx

**Special notes for your reviewer**:
test this API in EIP resource

**Release note**:

```release-note

```

## PR Checklist

* [ ] Tests added/passed.
* [ ] Documentation updated.
* [ ] Schema updated.

### CODE REVIEW

**Comment by ShiChangkuo** [comment]
@hmbig2 why we need this PR?

**Comment by hmbig2** [comment]
> @hmbig2 why we need this PR?
1. In the document, the type of those parameters  is array.  so correct it 
2. In order to support the datasource of eips

@ShiChangkuo

**Comment by ShiChangkuo** [comment]
I think the eips datasource is purpose to query all eips with simple parameters, such as eps_id and ip_version.
If users have got some public ips, it's better to use `huaweicloud_vpc_eip` data source.

**Comment by hmbig2** [comment]
> I think the eips datasource is purpose to query all eips with simple parameters, such as eps_id and ip_version. If users have got some public ips, it's better to use `huaweicloud_vpc_eip` data source.

This PR just make the sdk be consistent with api document.
huaweicloud_vpc_eips is in other PR. maybe user knows some public ips , but the tags specifies which group those resources belong to, so  those filters will been useful

**Pull request merged**
