### PR TITLE
fix(workspace/user): supplement 400 error for checkdeleted and schema supports description parameter

### PR DESCRIPTION
**Pull request by wuzhuanhong**
**What this PR does / why we need it**:
1. Add 'description' paramster to schema.
2. Add the CheckDeleted logical for this resource.

**Which issue this PR fixes**:
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
fixes #xxx

**Special notes for your reviewer**:

**Release note**:

```release-note

```

## PR Checklist

* [x] Tests added/passed.

```
make testacc TEST=./huaweicloud/services/acceptance/workspace TESTARGS='-run TestAccUser_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud/services/acceptance/workspace -v -run TestAccUser_basic -timeout 360m -parallel 4
=== RUN   TestAccUser_basic
--- PASS: TestAccUser_basic (167.71s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/acceptance/workspace 167.780s
```

* [ ] Documentation updated.
* [x] Schema updated.
* [ ] CheckDeleted.

  - **a. During query operation (Read Context)**
    aa. Resource not found
The user does not exist.
image

    ab. Related resources (parent resources) not found
    The Workspace service does not exist.
image

  - **b. During delete/disassociate/unbind operation (Delete Context)**
    ba. Resource not found
image

### CODE REVIEW

**Comment by dengyali0125** [comment]
LGTM

**Comment by wuzhuanhong** [comment]
make testacc TEST=./huaweicloud/services/acceptance/workspace TESTARGS='-run TestAccUser_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud/services/acceptance/workspace -v -run TestAccUser_basic -timeout 360m -parallel 4
=== RUN   TestAccUser_basic
--- PASS: TestAccUser_basic (153.57s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/acceptance/workspace 153.665s

**Comment by Lance52259** [comment]
please conside this PR title:
400 error supplement for checkdeleted and schema supports description param

**Pull request merged**
