### PR TITLE
Fix cdn resource missing issue

### PR DESCRIPTION
**Pull request by niuzhenguo**

### CODE REVIEW

**Comment by lyc0221** [comment]
@niuzhenguo Thank you for fixing it!

But `terraform init`, the provider is not the new version. And I try to clone master and make build , it will be deleted.

How to do ?

**Comment by niuzhenguo** [comment]
@lyc0221 That's weird, did you set the version in provider configuration?

**Comment by lyc0221** [comment]
no, 

image

**Comment by niuzhenguo** [comment]
So, where is the provider after your initialized, I mean the new downloaded provider. Maybe you can try to replace there.

**Comment by lyc0221** [comment]
`cp /Users/lyc/code/go/bin/terraform-provider-huaweicloud .terraform/plugins/darwin_amd64/terraform-provider-huaweicloud_v1.14.0_x4`

after I replaced by `cp`, it reports this error

```
Error: Could not satisfy plugin requirements


Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".



Error: provider.huaweicloud: new or changed plugin executable
```

**Comment by lyc0221** [comment]
oh, it's ok after `terraform init`

Thank you very much!!!

**Pull request merged**
