### PR TITLE
feat(workspace/app): add data source to get list of the image servers

### PR DESCRIPTION
**Pull request by wuzhuanhong**
**What this PR does / why we need it**:

Add new datasource to get the list of the image server of the Workspace APP.

**Which issue this PR fixes**:
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
fixes #xxx

**Special notes for your reviewer**:

**Release note**:

```release-note
1. add new datasource to get image servers.
2. add correponding document and acceptance test.
```

## PR Checklist

* [x] Tests added/passed.

```
$ ./scripts/coverage.sh -o workspace -f TestAccDataSourceAppImageServers_basic
Prepare to calculate the coverage the following command:
TF_ACC=1 go test "./huaweicloud/services/acceptance/workspace" -v -coverprofile="./huaweicloud/services/acceptance/workspace/workspace_coverage.cov" -coverpkg="./huaweicloud/services/workspace" -run TestAccDataSourceAppImageServers_basic -timeout 360m -parallel 10
=== RUN   TestAccDataSourceAppImageServers_basic
=== PAUSE TestAccDataSourceAppImageServers_basic
=== CONT  TestAccDataSourceAppImageServers_basic
--- PASS: TestAccDataSourceAppImageServers_basic (864.69s)
PASS
coverage: 7.6% of statements in ./huaweicloud/services/workspace
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/acceptance/workspace 864.776s        coverage: 7.6% of statements in ./huaweicloud/services/workspace
```

* [x] Documentation updated.
* [x] Schema updated.
* [ ] CheckDeleted.

  - **a. During query operation (Read Context)**
    aa. Resource not found
    \>>>>>> Paste the screenshot here <<<<<<

    
  - **b. During delete/disassociate/unbind operation (Delete Context)**
    ba. Resource not found
    \>>>>>> Paste the screenshot here <<<<<<

### CODE REVIEW

**Comment by wuzhuanhong** [comment]
./scripts/coverage.sh -o workspace -f TestAccDataSourceAppImageServers_basic
Prepare to calculate the coverage the following command:
TF_ACC=1 go test "./huaweicloud/services/acceptance/workspace" -v -coverprofile="./huaweicloud/services/acceptance/workspace/workspace_coverage.cov" -coverpkg="./huaweicloud/services/workspace" -run TestAccDataSourceAppImageServers_basic -timeout 360m -parallel 10
=== RUN   TestAccDataSourceAppImageServers_basic
=== PAUSE TestAccDataSourceAppImageServers_basic
=== CONT  TestAccDataSourceAppImageServers_basic
--- PASS: TestAccDataSourceAppImageServers_basic (833.15s)
PASS
coverage: 6.5% of statements in ./huaweicloud/services/workspace
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/acceptance/workspace 833.255s        coverage: 6.5% of statements in ./huaweicloud/services/workspace

**Comment by wuzhuanhong** [comment]
./scripts/coverage.sh -o workspace -f TestAccDataSourceAppImageServers_basic
Prepare to calculate the coverage the following command:
TF_ACC=1 go test "./huaweicloud/services/acceptance/workspace" -v -coverprofile="./huaweicloud/services/acceptance/workspace/workspace_coverage.cov" -coverpkg="./huaweicloud/services/workspace" -run TestAccDataSourceAppImageServers_basic -timeout 360m -parallel 10
=== RUN   TestAccDataSourceAppImageServers_basic
=== PAUSE TestAccDataSourceAppImageServers_basic
=== CONT  TestAccDataSourceAppImageServers_basic
--- PASS: TestAccDataSourceAppImageServers_basic (956.65s)
PASS
coverage: 6.5% of statements in ./huaweicloud/services/workspace
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/acceptance/workspace 956.721s        coverage: 6.5% of statements in ./huaweicloud/services/workspace

**Comment by WangLiNaruto** [comment]
LGTM

**Comment by wuzhuanhong** [comment]
./scripts/coverage.sh -o workspace -f TestAccDataSourceAppImageServers_basic
Prepare to calculate the coverage the following command:
TF_ACC=1 go test "./huaweicloud/services/acceptance/workspace" -v -coverprofile="./huaweicloud/services/acceptance/workspace/workspace_coverage.cov" -coverpkg="./huaweicloud/services/workspace" -run TestAccDataSourceAppImageServers_basic -timeout 360m -parallel 10
=== RUN   TestAccDataSourceAppImageServers_basic
=== PAUSE TestAccDataSourceAppImageServers_basic
=== CONT  TestAccDataSourceAppImageServers_basic
--- PASS: TestAccDataSourceAppImageServers_basic (778.37s)
PASS
coverage: 5.6% of statements in ./huaweicloud/services/workspace
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/acceptance/workspace 778.439s        coverage: 5.6% of statements in ./huaweicloud/services/workspace

**Pull request merged**
