### PR TITLE
feat(workspace/app): add data source to query application groups

### PR DESCRIPTION
**Pull request by wuzhuanhong**
**What this PR does / why we need it**:
Add new data source to get the list of the application groups.

**Which issue this PR fixes**:
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
fixes #xxx

**Special notes for your reviewer**:

**Release note**:

```release-note
1. add data source to query application groups.
2. add corresponding document and acceptance test.
```

## PR Checklist

* [x] Tests added/passed.

```
./scripts/coverage.sh -o workspace -f TestAccDataSourceWorkspaceAppGroups_basic
Prepare to calculate the coverage the following command:
TF_ACC=1 go test "./huaweicloud/services/acceptance/workspace" -v -coverprofile="./huaweicloud/services/acceptance/workspace/workspace_coverage.cov" -coverpkg="./huaweicloud/services/workspace" -run TestAccDataSourceWorkspaceAppGroups_basic -timeout 360m -parallel 10
=== RUN   TestAccDataSourceWorkspaceAppGroups_basic
=== PAUSE TestAccDataSourceWorkspaceAppGroups_basic
=== CONT  TestAccDataSourceWorkspaceAppGroups_basic
--- PASS: TestAccDataSourceWorkspaceAppGroups_basic (76.86s)
PASS
coverage: 7.3% of statements in ./huaweicloud/services/workspace
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/acceptance/workspace 76.927s coverage: 7.3% of statements in ./huaweicloud/services/workspace
```

* [x] Documentation updated.
* [x] Schema updated.
* [ ] CheckDeleted.

  - **a. During query operation (Read Context)**
    aa. Resource not found
    \>>>>>> Paste the screenshot here <<<<<<

    
  - **b. During delete/disassociate/unbind operation (Delete Context)**
    ba. Resource not found
    \>>>>>> Paste the screenshot here <<<<<<

### CODE REVIEW

**Comment by dengyali0125** [comment]
LGTM

**Comment by wuzhuanhong** [comment]
./scripts/coverage.sh -o workspace -f TestAccDataSourceWorkspaceAppGroups_basic
Prepare to calculate the coverage the following command:
TF_ACC=1 go test "./huaweicloud/services/acceptance/workspace" -v -coverprofile="./huaweicloud/services/acceptance/workspace/workspace_coverage.cov" -coverpkg="./huaweicloud/services/workspace" -run TestAccDataSourceWorkspaceAppGroups_basic -timeout 360m -parallel 10
=== RUN   TestAccDataSourceWorkspaceAppGroups_basic
=== PAUSE TestAccDataSourceWorkspaceAppGroups_basic
=== CONT  TestAccDataSourceWorkspaceAppGroups_basic
--- PASS: TestAccDataSourceWorkspaceAppGroups_basic (77.80s)
PASS
coverage: 6.5% of statements in ./huaweicloud/services/workspace
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/acceptance/workspace 77.877s coverage: 6.5% of statements in ./huaweicloud/services/workspace

**Comment by WangLiNaruto** [comment]
LGTM

**Pull request merged**
