### PR TITLE
feat(workspace/app_group_authorization): add application group authorization resource

### PR DESCRIPTION
**Pull request by wuzhuanhong**
**What this PR does / why we need it**:

Add new resource to manage APP group authorization resource.

When `accounts` contains non-existent objects，the error message is as follows:
image

**Which issue this PR fixes**:
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
fixes #xxx

**Special notes for your reviewer**:

**Release note**:

```release-note
1. add new resource.
2. add corresponding document and acceptance test.
3. not involving checkdeleted.
```

## PR Checklist

* [x] Tests added/passed.

```
./scripts/coverage.sh -o workspace -f TestAccResourceAppGroupAuthorization_
Prepare to calculate the coverage the following command:
TF_ACC=1 go test "./huaweicloud/services/acceptance/workspace" -v -coverprofile="./huaweicloud/services/acceptance/workspace/workspace_coverage.cov" -coverpkg="./huaweicloud/services/workspace" -run TestAccResourceAppGroupAuthorization_ -timeout 360m -parallel 10
=== RUN   TestAccResourceAppGroupAuthorization_basic
=== PAUSE TestAccResourceAppGroupAuthorization_basic
=== RUN   TestAccResourceAppGroupAuthorization_expectErr
=== PAUSE TestAccResourceAppGroupAuthorization_expectErr
=== CONT  TestAccResourceAppGroupAuthorization_basic
=== CONT  TestAccResourceAppGroupAuthorization_expectErr
--- PASS: TestAccResourceAppGroupAuthorization_expectErr (29.33s)
--- PASS: TestAccResourceAppGroupAuthorization_basic (48.78s)
PASS
coverage: 16.6% of statements in ./huaweicloud/services/workspace
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/acceptance/workspace 48.847s coverage: 16.6% of statements in ./huaweicloud/services/workspace
```

* [x] Documentation updated.
* [x] Schema updated.
* [ ] CheckDeleted.

  - **a. During query operation (Read Context)**
    aa. Resource not found
    \>>>>>> Paste the screenshot here <<<<<<

    
  - **b. During delete/disassociate/unbind operation (Delete Context)**
    ba. Resource not found
    \>>>>>> Paste the screenshot here <<<<<<

### CODE REVIEW

**Comment by wuzhuanhong** [comment]
./scripts/coverage.sh -o workspace -f TestAccResourceAppGroupAuthorization_
Prepare to calculate the coverage the following command:
TF_ACC=1 go test "./huaweicloud/services/acceptance/workspace" -v -coverprofile="./huaweicloud/services/acceptance/workspace/workspace_coverage.cov" -coverpkg="./huaweicloud/services/workspace" -run TestAccResourceAppGroupAuthorization_ -timeout 360m -parallel 10
=== RUN   TestAccResourceAppGroupAuthorization_basic
=== PAUSE TestAccResourceAppGroupAuthorization_basic
=== RUN   TestAccResourceAppGroupAuthorization_expectErr
=== PAUSE TestAccResourceAppGroupAuthorization_expectErr
=== CONT  TestAccResourceAppGroupAuthorization_basic
=== CONT  TestAccResourceAppGroupAuthorization_expectErr
--- PASS: TestAccResourceAppGroupAuthorization_expectErr (34.23s)
--- PASS: TestAccResourceAppGroupAuthorization_basic (53.02s)
PASS
coverage: 15.4% of statements in ./huaweicloud/services/workspace
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/acceptance/workspace 53.084s coverage: 15.4% of statements in ./huaweicloud/services/workspace

**Comment by WangLiNaruto** [comment]
LGTM

**Comment by Alice1319** [comment]
LGTM

**Comment by dengyali0125** [comment]
LGTM

**Comment by dengyali0125** [comment]
LGTM

**Pull request merged**
