### PR TITLE
fix(cdn/domain): clean up unsupported arguments

### PR DESCRIPTION
**Pull request by niuzhenguo**
**What this PR does / why we need it**:

**Which issue this PR fixes**:
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
fixes #xxx

**Special notes for your reviewer**:
incompatible changes

**Release note**:

```release-note

```

## PR Checklist

* [x] Tests added/passed.
* [ ] Documentation updated.
* [x] Schema updated.

## Acceptance Steps Performed

```
make testacc TEST='./huaweicloud' TESTARGS='-run=TestAccCdnDomain_basic'
...
=== RUN   TestAccCdnDomain_basic
--- PASS: TestAccCdnDomain_basic (130.13s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud       130.163s

```

### CODE REVIEW

**Review by chengxiangdong — COMMENTED** [review]
is there any incompatibility problems with `cname` and `domain_status` in the old script ?

**Comment by niuzhenguo** [comment]
this is indeed a breaking change, but seems will not affect original scripts as cname and domain_status are attributes according our documents.

**Comment by chengxiangdong** [comment]
i took a look at the document, and these two fields were not provided. 
There will be no compatibility problems.

**Review by Jason-Zhang9309 — COMMENTED** [review]
LGTM

**Pull request merged**
