### PR TITLE
resource iam agency

### PR DESCRIPTION
**Pull request by zengchen1024**
support resource of agency

### CODE REVIEW

**Comment by zengchen1024** [comment]
It is not very good to test this pr in acceptance test, because it needs two user account to create an agency. But I have tested it using terraform tool and it passed.

**Comment by zengchen1024** [comment]
@niuzhenguo Could you take a look at this pr, thanks!

**Comment by niuzhenguo** [comment]
@zengchen1024 Please resolve conflicts first!

**Comment by zengchen1024** [comment]
@niuzhenguo Done

**Pull request merged**
