### PR TITLE
fix(cdn): add a new available type

### PR DESCRIPTION
**Pull request by chengxiangdong**
**What this PR does / why we need it**:

**Which issue this PR fixes**:
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
fixes #xxx

**Special notes for your reviewer**:

**Release note**:

```release-note
Add whole site type for domain name in CDN.
```

## PR Checklist

* [ ] Tests added/passed.
* [ ] Documentation updated.
* [x] Schema updated.

## Acceptance Steps Performed

```
make testacc TEST='./huaweicloud' TESTARGS='-run TestAccCdnDomain_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./huaweicloud -v -run TestAccCdnDomain_basic -timeout 360m -parallel 4
=== RUN   TestAccCdnDomain_basic
=== PAUSE TestAccCdnDomain_basic
=== CONT  TestAccCdnDomain_basic
--- PASS: TestAccCdnDomain_basic (488.64s)
PASS
ok      github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud       489.139s

```

### CODE REVIEW

**Comment by niuzhenguo** [comment]
should update docs as well.

**Comment by niuzhenguo** [comment]
and seems this should be `fix` instead of `chore`

**Comment by chengxiangdong** [comment]
> should update docs as well.

yes, docs is very important.

**Review by Jason-Zhang9309 — COMMENTED** [review]
LGTM

**Pull request merged**
