### PR TITLE
Add private/public IP attributes to CCE node

### LINKED ISSUE #118: huaweicloud_cce_node_v3: dial tcp :22: connectex: No connection could be made because the target machine actively refused it.
Hi there,

### Affected Resource(s)
huaweicloud_cce_node_v3

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

##worker nodes
resource "huaweicloud_cce_node_v3" "cce_node" {
    depends_on         = [ "huaweicloud_cce_cluster_v3.cluster_1" ]
    cluster_id         = "${huaweicloud_cce_cluster_v3.cluster_1.id}"
    name               = "${var.cce_cluster_name}-node${count.index}"
    #os: see https://github.com/terraform-providers/terraform-provider-huaweicloud/issues/97
    #os                 = "${var.cce_node_os}" #EulerOS 2.2 or CentOS 7.1 or CentOS 7.4?
    flavor_id          = "${var.worker_flavor_id}"
    iptype             = "5_bgp"
    count              = "${var.worker_node_capacity}"
    eip_count          = "1"
    billing_mode       = "0"
    availability_zone  = "cn-east-2b"
    key_pair           = "${var.key_pair_name}"
    labels             = "${var.tags}"
    root_volume        = {
                         size= 40,
                         volumetype= "SATA"
                         }
    sharetype          = "PER"
    bandwidth_size     = "100"
    bandwidth_charge_mode = "traffic"
    data_volumes       = [
                       {
                        size= "${var.CCE_worker_space_GB}",
                        volumetype= "SATA"
                       },
    ]

    #workaround for https://github.com/terraform-providers/terraform-provider-huaweicloud/issues/111#issuecomment-487438627 
    lifecycle {
    ignore_changes = [
      "eip_count",
    ]
  }
# }

#######################################################################
####Adding a provisioner block to install needed software socat on each worker node

  provisioner "remote-exec" {
    connection {
      type        = "ssh"
      timeout     = "780"
      user        = "root"
      private_key = "${file(var.private_key)}"
   }
 
   inline = [   
     "yum install -y socat",  
    ] 
   }
}
```

### Debug Output
log: 
[debug_log.zip](https://github.com/terraform-providers/terraform-provider-huaweicloud/files/3147869/debug_log.zip)

### Expected Behavior
After creating the 4 worker nodes with public-ips, logon with user _root_ and _privat_key_ ("${file(var.private_key)}" which points to pem file on my local workstation: "C:/Testinfo/AWS_Dathub_Vora/huawei_key_pairs/SLV-key-pairs-all.pem") should be done.

**Note:**
Connecting to the same nodes via putty and same pem file is working without issues

**But getting in terraform**
...
huaweicloud_cce_node_v3.cce_node[1] (remote-exec): Connecting to remote host via SSH...
huaweicloud_cce_node_v3.cce_node[1] (remote-exec):   Host:
huaweicloud_cce_node_v3.cce_node[1] (remote-exec):   User: root
huaweicloud_cce_node_v3.cce_node[1] (remote-exec):   Password: false
huaweicloud_cce_node_v3.cce_node[1] (remote-exec):   Private key: true
huaweicloud_cce_node_v3.cce_node[1] (remote-exec):   SSH Agent: false
huaweicloud_cce_node_v3.cce_node[1] (remote-exec):   Checking Host Key: false
huaweicloud_cce_node_v3.cce_node.0: Still creating... (9m20s elapsed)
huaweicloud_cce_node_v3.cce_node.2: Still creating... (9m20s elapsed)
huaweicloud_cce_node_v3.cce_node.3: Still creating... (9m20s elapsed)
huaweicloud_cce_node_v3.cce_node.1: Still creating... (9m20s elapsed)

Error: Error applying plan:

4 error(s) occurred:

* huaweicloud_cce_node_v3.cce_node[1]: timeout - last error: dial tcp :22: connectex: No connection could be made because the target machine actively refused it.
* huaweicloud_cce_node_v3.cce_node[0]: timeout - last error: dial tcp :22: connectex: No connection could be made because the target machine actively refused it.
* huaweicloud_cce_node_v3.cce_node[2]: timeout - last error: dial tcp :22: connectex: No connection could be made because the target machine actively refused it.
* huaweicloud_cce_node_v3.cce_node[3]: timeout - last error: dial tcp :22: connectex: No connection could be made because the target machine actively refused it.

### PR DESCRIPTION
**Pull request by niuzhenguo**
fixes #118

### CODE REVIEW

**Comment by Thomas999999** [comment]
Hi,
for me as a tester/user it is not quite sure when those fixes/adaptions were live in production code, for example also the issues you fixed for authentication_mode & os key are still not working:

C:\Testinfo\AWS_Dathub_Vora\Huawei-Cluster\cluster-dev>terraform plan
Error: huaweicloud_cce_cluster_v3.cluster_1: : invalid or unknown key: authentication_mode

C:\Testinfo\AWS_Dathub_Vora\Huawei-Cluster\cluster-dev>terraform plan
Error: huaweicloud_cce_node_v3.cce_node[0]: : invalid or unknown key: os
Error: huaweicloud_cce_node_v3.cce_node[1]: : invalid or unknown key: os
Error: huaweicloud_cce_node_v3.cce_node[2]: : invalid or unknown key: os
Error: huaweicloud_cce_node_v3.cce_node[3]: : invalid or unknown key: os

Thus were do I see as user/tester that your fixes were not only done, but also live for production use?
Thanks for all your effort!

**Comment by niuzhenguo** [comment]
@Thomas999999 You can build the provider youself to test according to the README

**Comment by niuzhenguo** [comment]
@Thomas999999 V1.5.0 just released, pelase have a try!

**Comment by Thomas999999** [comment]
seems that version 1.5 is not yet fetched:
C:\Testinfo\AWS_Dathub_Vora\Huawei-Cluster\cluster-dev>terraform init

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

*** provider.huaweicloud: version = "~> 1.4"**
* provider.null: version = "~> 2.1"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

C:\Testinfo\AWS_Dathub_Vora\Huawei-Cluster\cluster-dev>terraform plan

Error: huaweicloud_cce_cluster_v3.cluster_1: : invalid or unknown key: authentication_mode



Error: huaweicloud_cce_node_v3.cce_node[0]: : invalid or unknown key: os



Error: huaweicloud_cce_node_v3.cce_node[1]: : invalid or unknown key: os



Error: huaweicloud_cce_node_v3.cce_node[2]: : invalid or unknown key: os



Error: huaweicloud_cce_node_v3.cce_node[3]: : invalid or unknown key: os

**Comment by niuzhenguo** [comment]
@Thomas999999 Please use `terraform init -upgrade=true` to upgrade to 1.5.0

**Pull request merged**
